// src/pages/DrugProfile.jsx — full label view + mechanism visualizer + FAERS chart
import { useEffect, useMemo, useState } from 'react'
import { api } from '../api.js'
import MoaGraph from '../MoaGraph.jsx'
import { useStatus } from '../App.jsx'
import { Citations, DisclaimerBar, ErrorBox, Md, Spinner } from '../ui.jsx'

const TABS = [['profile', '📄 Label Profile'], ['moa', '⚛️ Mechanism'], ['safety', '📊 Safety Signals']]

export default function DrugProfile({ spl }) {
  const [label, setLabel] = useState(null)
  const [error, setError] = useState(null)
  const [tab, setTab] = useState('profile')
  const status = useStatus()

  useEffect(() => {
    if (!spl) return
    setLabel(null); setError(null)
    api.label(spl).then(setLabel).catch(setError)
  }, [spl])

  if (!spl) return <p>No drug selected. <a href="#/search">Search first</a>.</p>
  if (error) return <><ErrorBox error={error} /><a href="#/search">← back to search</a></>
  if (!label) return <Spinner label="Fetching FDA label…" />

  const drugName = (label.genericName || '').toLowerCase()
  return (
    <section aria-label="Drug profile">
      <h1>{label.genericName || label.documentTitle} {label.brandNames[0] ? <span className="muted" style={{ fontSize: '.65em' }}>as {label.brandNames[0]}</span> : null}</h1>
      <div className="kv card" style={{ padding: 14 }}>
        <dt>Brand names</dt><dd>{label.brandNames.join(', ') || '—'}</dd>
        <dt>Manufacturer</dt><dd>{label.manufacturer || '—'}</dd>
        <dt>Route / form</dt><dd>{[label.route, label.dosageForm].filter(Boolean).join(' · ') || '—'}</dd>
        <dt>Active ingredient</dt><dd>{label.activeIngredient || '—'}</dd>
        <dt>RxNorm</dt><dd>{label.rxcui.length ? label.rxcui.map((id) => <a key={id} className="chip" href={`https://rxnav.nlm.nih.gov/REST/rxcui/${id}/properties.json`} target="_blank" rel="noopener noreferrer">RxCUI {id}</a>) : '—'}</dd>
        <dt>Label version</dt><dd>{label.effectiveTime ? `${label.effectiveTime.replace(/(\d{4})(\d{2})(\d{2}).*/, '$1-$2-$3')} (SPL set ${label.splId.slice(0, 8)}…)` : '—'}</dd>
      </div>
      <div className="chips" role="tablist" aria-label="Profile sections">
        {TABS.map(([k, l]) => (
          <button key={k} role="tab" aria-selected={tab === k} className={tab === k ? 'btn small' : 'btn small secondary'} onClick={() => setTab(k)} style={{ borderRadius: 999 }}>{l}</button>
        ))}
      </div>

      {tab === 'profile' && <LabelTab label={label} />}
      {tab === 'moa' && <MoaTab drug={drugName} status={status} label={label} />}
      {tab === 'safety' && <SafetyTab drug={drugName} label={label} />}
      <DisclaimerBar />
    </section>
  )
}

function LabelTab({ label }) {
  const [openAll, setOpenAll] = useState(false)
  const primary = ['indications_and_usage', 'contraindications', 'drug_interactions', 'warnings_and_cautions']
  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2>FDA Structured Product Label</h2>
        <button className="btn small secondary" onClick={() => setOpenAll(!openAll)}>{openAll ? 'Collapse all' : 'Expand all'}</button>
      </div>
      {label.sections.map((s) => (
        <details key={s.key} className="section" open={openAll || primary.includes(s.key)}>
          <summary>{s.title}<span className="muted small"> {s.text.length.toLocaleString()} chars</span></summary>
          <div className="body">{s.text.slice(0, 20000)}</div>
        </details>
      ))}
      <Citations items={label.citations} />
      <p className="small muted">Section text is HTML-stripped directly from the openFDA label API. “Last updated” reflects the SPL effective date.</p>
    </div>
  )
}

function MoaTab({ drug, status, label }) {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [loading, setLoading] = useState(true)
  const [gen, setGen] = useState(false)
  useEffect(() => {
    setLoading(true); setError(null)
    api.mechanism(drug).then(setData).catch(setError).finally(() => setLoading(false))
  }, [drug])

  if (loading) return <div className="card"><Spinner label={`Building mechanism graph for ${drug}…`} /></div>
  if (error) return <div className="card"><ErrorBox error={error} /></div>

  const graph = data.graph
  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
        <h2 style={{ margin: 0 }}>Mechanism of Action <span className={`chip ${data.source === 'curated' ? 'minor' : 'moderate'}`} title={data.source === 'curated' ? 'Curated pharmacology cross-checked against label' : 'Generated by the AI agent — verify'}>{data.source}</span></h2>
        {status.agent?.configured && (
          <button className="btn small secondary" disabled={gen} onClick={() => {
            setGen(true)
            api.regenerateMechanism(drug).then((d) => d.graph && setData(d)).catch(setError).finally(() => setGen(false))
          }}>{gen ? 'Generating…' : '🤖 Regenerate with AI'}</button>
        )}
      </div>
      {graph
        ? <>
          <p>{graph.summary}</p>
          <MoaGraph graph={graph} />
          {graph.note && <p className="small muted">⚠️ {graph.note}</p>}
        </>
        : <>
          <p className="muted">No interactive graph available for this drug without the AI agent. Label mechanism text:</p>
          <Md text={data.labelSummary} />
          {!status.agent?.configured && <p className="small muted">Run the desktop version with a model key to let Qwen generate an interactive diagram for any drug.</p>}
        </>}
      <Citations items={data.citations || graph?.citations || label.citations} />
    </div>
  )
}

function SafetyTab({ drug, label }) {
  const [faers, setFaers] = useState(null)
  const [error, setError] = useState(null)
  useEffect(() => { api.faers(drug).then(setFaers).catch(setError) }, [drug])
  const max = useMemo(() => Math.max(1, ...(faers?.results || []).map((r) => r.count)), [faers])
  const adverse = label.sections.find((s) => s.key === 'adverse_reactions')
  return (
    <div className="card">
      <h2>FAERS: most-reported adverse events</h2>
      {error && <ErrorBox error={error} />}
      {faers && !faers.results.length && <p className="muted">No FAERS reports indexed for this exact generic name.</p>}
      {faers?.results.map((r) => (
        <div className="bar-row" key={r.term} title={`${r.count.toLocaleString()} reports`}>
          <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.term.toLowerCase()}</span>
          <span className="bar-track"><span className="bar-fill" style={{ width: `${(r.count / max) * 100}%` }} /></span>
          <span className="muted small">{r.count.toLocaleString()}</span>
        </div>
      ))}
      {faers && <p className="small muted">{faers.results.length} terms · voluntary reports, <strong>no proven causality</strong> · <a href={`https://api.fda.gov/drug/event.json?search=${encodeURIComponent(`patient.drug.openfda.generic_name:"${drug}"`)}&count=patient.reaction.reactionmeddrapt.exact&limit=8`} target="_blank" rel="noopener noreferrer">raw query ↗</a></p>}
      {adverse && (
        <details className="section" style={{ marginTop: 14 }}>
          <summary>Label Adverse Reactions section</summary>
          <div className="body">{adverse.text.slice(0, 12000)}</div>
        </details>
      )}
      <Citations items={label.citations.slice(0, 2)} />
    </div>
  )
}
